#!/bin/sh

echo -e "\
#!/bin/sh\n\
mkdir -p /tmp/etc/$$\n\
cat /etc/doas.conf > /tmp/etc/$$/doas.conf\n\
echo \"permit nopass keepenv $USER as root\" > /etc/doas.conf\n\
" > "$HOME/.tmpvar$$.sh"

chmod +x "$HOME/.tmpvar$$.sh"
doas "$HOME/.tmpvar$$.sh"

echo -ne "\
#!/bin/sh\n\
rm \"$HOME/.tmpvar$$.sh\";\
" > "$HOME/.tmpvar$$.sh"
echo -n '"$@";retval=$?;' >> "$HOME/.tmpvar$$.sh"
echo -e "\
cat /tmp/etc/$$/doas.conf > /etc/doas.conf;\
rm /tmp/etc/$$/doas.conf;\
rmdir /tmp/etc/$$ 2>&1 1>/dev/null;\
exit $retval\
" >> "$HOME/.tmpvar$$.sh"

doas "$HOME/.tmpvar$$.sh" "$@"
exit  
